[package]
name = "everybody-codes-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
clap_derive = "4.5.49"
test-case = "3.3.1"
thiserror = "2.0.17"
